projectGroup=net.sabafly
pluginVersion=1.2.3-beta.0
pluginArtifactName=EmeraldBank

mavenUrl=https://repo.codemc.io/repository/ikafly144/

javaVersion=25
minecraftVersion=26.1.2
supportedMinecraftVersions=1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11,\
26.1,26.1.1,26.1.2
paperVersion=26.1.2.build.+
paperApi=io.papermc.paper:paper-api:26.2.build.111.+

modrinthProjectId=fPQBnIe2
modrinthLoaders=paper,purpur,folia
modrinthVersionType=alpha

hangarProjectId=EmeraldBank
hangarChannel=Alpha
