name: EmeraldBank
authors:
  - ikafly144
version: '${version}'
main: net.sabafly.emeraldbank.EmeraldBank
bootstrapper: net.sabafly.emeraldbank.EmeraldBootstrapper
loader: net.sabafly.emeraldbank.EmeraldLoader
api-version: '1.21'
load: STARTUP
dependencies:
  bootstrap:
    Essentials:
      load: BEFORE
      required: false
  server:
    Vault:
      load: BEFORE
      required: true
    OpenInv:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Essentials:
      load: BEFORE
      required: false
permissions:
  emeraldbank.bypass:
    default: false
    description: Allows the player to bypass the EmeraldBank command
    children:
      emeraldbank.bypass.cost:
        default: false
      emeraldbank.bypass.deposit:
        default: false
      emeraldbank.bypass.member:
        default: false
      emeraldbank.bypass.owner:
        default: false
  emeraldbank.admin:
    default: op
    description: Allows the player to use all EmeraldBank command
    children:
      emeraldbank.balance.all: true
      emeraldbank.wallet.balance.all: true
      emeraldbank.reload: true
      emeraldbank.default:
        default: true
        description: Allows the player to use the EmeraldBank command
        children:
          emeraldbank.balance: true
          emeraldbank.pay: true
          emeraldbank.leaderboard: true
          emeraldbank.wallet:
            default: true
            description: Allows the player to use the EmeraldBank command
            children:
              emeraldbank.wallet.balance: true
              emeraldbank.wallet.add: true
              emeraldbank.wallet.withdraw: true
          emeraldbank.banking:
            default: true
            description: Allows the player to use the EmeraldBank command
            children:
              emeraldbank.banking.account:
                default: true
                description: Allows the player to use the EmeraldBank command
                children:
                  emeraldbank.banking.account.create: true
                  emeraldbank.banking.account.delete: true
                  emeraldbank.banking.account.add: true
                  emeraldbank.banking.account.remove: true
                  emeraldbank.banking.account.list: true
                  emeraldbank.banking.account.transfer: true
              emeraldbank.banking.withdraw: true
              emeraldbank.banking.deposit: true
              emeraldbank.banking.balance: true
              emeraldbank.banking.send: true
              emeraldbank.banking.pay: true
